### PR TITLE
Update to version 1.1.2

### PR DESCRIPTION
**Pull request by acordonez**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by acordonez** [comment]
@conda-forge-admin, please rerender

**Comment by lee1043** [comment]
@acordonez thank you for working on this. Should we consider dropping python >= 3.11 until we completed drop cdms?

**Comment by acordonez** [comment]
@lee1043 Got an error for not having the 'packaging' dependency:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1078170&view=logs&j=d818e662-7181-5ce9-b265-50d03742b7af&t=367317f3-9b77-59ac-9e12-e56370c98acd&l=1359
Is [this](https://anaconda.org/conda-forge/packaging) the package we need?

**Comment by lee1043** [comment]
> @lee1043 Got an error for not having the 'packaging' dependency: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1078170&view=logs&j=d818e662-7181-5ce9-b265-50d03742b7af&t=367317f3-9b77-59ac-9e12-e56370c98acd&l=1359 Is [this](https://anaconda.org/conda-forge/packaging) the package we need?

@acordonez thank you for investigating. Interesting as I thought the `packaging` was one of default python library. 

It is used to check numpy version, imported [here](https://github.com/CLIVAR-PRP/ENSO_metrics/blob/e8ba34e7dac9630f65e1a959de0e155454cea522/lib/EnsoUvcdatToolsLib.py#L6) and used [here](https://github.com/CLIVAR-PRP/ENSO_metrics/blob/e8ba34e7dac9630f65e1a959de0e155454cea522/lib/EnsoUvcdatToolsLib.py#L17). 

Can we add that to the dependency list?

**Comment by lee1043** [comment]
Looks like `packaging` is on conda-forge

https://github.com/conda-forge/packaging-feedstock

https://anaconda.org/conda-forge/packaging/

This tool is specifically used to [compare version numbers](https://packaging.pypa.io/en/stable/version.html) to decide latest, because they can be non-regular float numbers like `1.2.3`.

**Review by lee1043 — APPROVED** [review]

**Comment by acordonez** [comment]
Failures in Python 3.11 and 3.12 are expected due to cdat dependencies.

**Pull request merged**
